[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "poetry", "nodejs_24"]

[phases.install]
cmds = [
  "poetry install --no-root",
  "cd shopsmart && rm -rf node_modules package-lock.json && npm install && npm run build"
]

[phases.build]
cmds = ["poetry run python manage.py collectstatic --noinput"]

[start]
cmd = "poetry run python manage.py migrate --noinput && poetry run gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
