# Generated by Django 6.0.4 on 2026-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup_simulated', 'Topup Simulated'), ('order_payment', 'Order Payment'), ('sale_proceeds', 'Sale Proceeds'), ('refund_in', 'Refund In'), ('refund_out', 'Refund Out'), ('withdrawal_hold', 'Withdrawal Hold'), ('withdrawal_release', 'Withdrawal Release'), ('withdrawal_settled', 'Withdrawal Settled'), ('platform_fee', 'Platform Fee')], max_length=50),
        ),
    ]
