# Generated by Django 6.0.4 on 2026-05-23 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_wallettransaction_options_address_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
